repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black -S .
        language: system
        pass_filenames: false
      - id: isort
        name: isort
        entry: poetry run isort .
        language: system
      - id: flake8
        name: flake8
        entry: poetry run flake8 .
        language: system

